kernelsu-objs := core/init.o

kernelsu-objs += compat/samsung_kdp.o
kernelsu-objs += compat/samsung_defex.o
kernelsu-objs += compat/samsung_rkp.o

kernelsu-objs += feature/kernel_umount.o
kernelsu-objs += feature/sulog.o
kernelsu-objs += feature/sucompat.o

kernelsu-objs += hook/lsm_hook.o
kernelsu-objs += hook/setuid_hook.o
kernelsu-objs += hook/syscall_event_bridge.o
kernelsu-objs += hook/syscall_hook_manager.o
kernelsu-objs += hook/tp_marker.o
ifeq ($(CONFIG_ARM64),y)
kernelsu-objs += hook/arm64/patch_memory.o
kernelsu-objs += hook/arm64/syscall_hook.o
else ifeq ($(CONFIG_X86_64),y)
kernelsu-objs += hook/x86_64/patch_memory.o
kernelsu-objs += hook/x86_64/syscall_hook.o
else ifeq ($(CONFIG_RISCV),y)
kernelsu-objs += hook/riscv64/patch_memory.o
kernelsu-objs += hook/riscv64/syscall_hook.o
endif
kernelsu-objs += extras.o

kernelsu-objs += infra/file_wrapper.o
kernelsu-objs += infra/event_queue.o
kernelsu-objs += infra/seccomp_cache.o
kernelsu-objs += infra/su_mount_ns.o
kernelsu-objs += infra/symbol_resolver.o

ifneq ($(CONFIG_KSU_DISABLE_MANAGER),y)
kernelsu-objs += manager/apk_sign.o
kernelsu-objs += manager/pkg_observer.o
kernelsu-objs += manager/throne_tracker.o
endif

kernelsu-objs += policy/allowlist.o
kernelsu-objs += policy/app_profile.o
kernelsu-objs += policy/feature.o

kernelsu-objs += runtime/boot_event.o
kernelsu-objs += runtime/ksud_integration.o

kernelsu-objs += selinux/selinux.o
kernelsu-objs += selinux/rules.o
kernelsu-objs += selinux/sepolicy.o

kernelsu-objs += sulog/event.o
kernelsu-objs += sulog/fd.o

kernelsu-objs += supercall/dispatch.o
kernelsu-objs += supercall/perm.o
kernelsu-objs += supercall/supercall.o

kernelsu-objs += feature/adb_root.o

kernelsu-objs += feature/selinux_hide.o

ifdef KBUILD_EXTMOD
ifeq ($(CONFIG_KSU_DISABLE_MANAGER),y)
ccflags-y += -DCONFIG_KSU_DISABLE_MANAGER=1
endif
ifeq ($(CONFIG_KSU_DISABLE_POLICY),y)
ccflags-y += -DCONFIG_KSU_DISABLE_POLICY=1
endif
ifeq ($(CONFIG_KSU_DEBUG),y)
ccflags-y += -DCONFIG_KSU_DEBUG=1
endif
ifeq ($(CONFIG_KSU_X86_PATCH_SYSCALL_DISPATCHER),y)
ccflags-y += -DCONFIG_KSU_X86_PATCH_SYSCALL_DISPATCHER=1
endif
ifeq ($(CONFIG_KSU_SAMSUNG_KDP),y)
ccflags-y += -DCONFIG_KSU_SAMSUNG_KDP=1
endif
ifeq ($(CONFIG_KSU_SAMSUNG_RKP),y)
ccflags-y += -DCONFIG_KSU_SAMSUNG_RKP=1
endif
ifeq ($(CONFIG_KSU_SAMSUNG_DEFEX),y)
ccflags-y += -DCONFIG_KSU_SAMSUNG_DEFEX=1
endif
ifeq ($(CONFIG_KSU_SAMSUNG_NO_PATCH_TEXT),y)
ccflags-y += -DCONFIG_KSU_SAMSUNG_NO_PATCH_TEXT=1
endif
endif

ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h

ifneq ($(KBUILD_EXTMOD),)
# 6.18 exports the external module source as srcroot when M/MO are used.
ifneq ($(srcroot),)
KSU_KERNEL_DIR := $(srcroot)
else
KSU_KERNEL_DIR := $(KBUILD_EXTMOD)
endif
else ifeq ($(filter /%,$(src)),)
KSU_KERNEL_DIR := $(srctree)/$(src)
else
KSU_KERNEL_DIR := $(src)
endif

ccflags-y += -I$(KSU_KERNEL_DIR) -I$(KSU_KERNEL_DIR)/include -I$(KSU_KERNEL_DIR)/..

obj-$(CONFIG_KSU) += kernelsu.o

LPATH := /usr/bin/env PATH="$$PATH":/usr/bin:/usr/local/bin
MDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

# Check if this is a git repository
# Try to detect Git repo intelligently
GIT_ROOT := $(shell cd $(MDIR) && $(LPATH) git rev-parse --show-toplevel 2>/dev/null)
ifneq ($(GIT_ROOT),)
KERNEL_GIT_ROOT := $(shell cd $(srctree) && $(LPATH) git rev-parse --show-toplevel 2>/dev/null)
ifneq ($(GIT_ROOT),$(KERNEL_GIT_ROOT))
# Only set version if it's a different repo from kernel
$(shell cd $(GIT_ROOT) && [ -f .git/shallow ] && $(LPATH) git fetch --unshallow 2>/dev/null || true)
KSU_GIT_VERSION := $(shell cd $(GIT_ROOT) && $(LPATH) git rev-list --count HEAD 2>/dev/null)
KSU_GIT_TAG := $(shell cd $(GIT_ROOT) && $(LPATH) git describe --tags --abbrev=0 2>/dev/null)
KSU_GIT_VERSION_VALID := 1
$(info -- KernelSU-Next Git repo detected at: $(GIT_ROOT))
endif
endif

# Calculate version if git version is available
ifdef KSU_GIT_VERSION_VALID
# ksu_version: major * 30000 + git version for historical reasons
$(eval KSU_VERSION=$(shell expr 30000 + $(KSU_GIT_VERSION)))
$(info -- KernelSU-Next version: $(KSU_VERSION))
ccflags-y += -DKSU_VERSION=$(KSU_VERSION)
else
# If there is no .git directory, use default version
$(warning "KSU_GIT_VERSION not defined! It is better to make KernelSU-Next a git repository!")
KSU_VERSION_FALLBACK := 1
$(info -- KernelSU-Next version fallback: $(KSU_VERSION_FALLBACK))
ccflags-y += -DKSU_VERSION=$(KSU_VERSION_FALLBACK)
endif

ifdef KSU_GIT_VERSION_VALID
$(eval KSU_VERSION_TAG=$(KSU_GIT_TAG))
$(info -- KernelSU-Next tag: $(KSU_VERSION_TAG))
ccflags-y += -DKSU_VERSION_TAG=\"$(KSU_VERSION_TAG)\"
else
$(warning "KSU_VERSION_TAG not defined! It is better to make KernelSU-Next a git submodule!")
KSU_VERSION_TAG_FALLBACK := v0.0.1
$(info -- KernelSU-Next tag fallback: $(KSU_VERSION_TAG_FALLBACK))
ccflags-y += -DKSU_VERSION_TAG=\"$(KSU_VERSION_TAG_FALLBACK)\"
endif

KSU_NEW_DCACHE_FLUSH := $(shell grep -q __flush_dcache_area $(srctree)/arch/arm64/include/asm/cacheflush.h ; echo $$?)
$(info -- KernelSU-Next new DCACHE flush: $(KSU_NEW_DCACHE_FLUSH))

ifndef KSU_NEXT_MANAGER_SIZE
KSU_NEXT_MANAGER_SIZE := 0x3e6
endif

ifndef KSU_NEXT_MANAGER_HASH
KSU_NEXT_MANAGER_HASH := 79e590113c4c4c0c222978e413a5faa801666957b1212a328e46c00c69821bf7
endif

ifdef KSU_MANAGER_PACKAGE
ccflags-y += -DKSU_MANAGER_PACKAGE=\"$(KSU_MANAGER_PACKAGE)\"
$(info -- KernelSU-Next Manager package name: $(KSU_MANAGER_PACKAGE))
endif

$(info -- KernelSU-Next Manager signature size: $(KSU_NEXT_MANAGER_SIZE))
$(info -- KernelSU-Next Manager signature hash: $(KSU_NEXT_MANAGER_HASH))

ccflags-y += -DEXPECTED_MANAGER_SIZE=$(KSU_NEXT_MANAGER_SIZE)
ccflags-y += -DEXPECTED_MANAGER_HASH=\"$(KSU_NEXT_MANAGER_HASH)\"

ccflags-y += -DKSU_NEW_DCACHE_FLUSH=$(KSU_NEW_DCACHE_FLUSH)

ccflags-y += -Wno-strict-prototypes -Wno-int-conversion -Wno-gcc-compat -Wno-missing-prototypes -Wno-missing-declarations
ccflags-y += -Wno-declaration-after-statement -Wno-unused-function -Wno-unused-variable

# Keep a new line here!! Because someone may append config
